apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-service
  namespace: default
  labels:
    app: embedding-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedding-service
  template:
    metadata:
      labels:
        app: embedding-service
    spec:
      containers:
        - name: embedding-service
          image: host.docker.internal:5000/embedding-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: WORKERS
              value: "4"
            - name: OMP_NUM_THREADS
              value: "1"
            - name: MKL_NUM_THREADS
              value: "1"
            - name: TORCH_NUM_THREADS
              value: "1"
          resources:
            requests:
              cpu: "500m"
              memory: "768Mi"
            limits:
              cpu: "2"
              memory: "1500Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
